### ISSUE TITLE
all widget under the same column after upgrade

### ISSUE THREAD

**Issue by sbenodiz** [AalianKhan/mushroom-strategy#232]
### What happened?

I used to have 3 columns in my dashboard, but after upgrading the latest version is all under the same column 

### Steps to reproduce

see image after upgrade 

<img width="1211" alt="Image" src="https://github.com/user-attachments/assets/5ddb24e2-3937-4f8d-805b-4d05279a6d2e" />

see yaml 

```
strategy:
  type: custom:mushroom-strategy
  options:
    chips:
      climate_count: false
      cover_count: false
      fan_count: false
      switch_count: false
      weather_entity: false
      light_count: true
    areas:
      rei_s_room:
        name: Rei room
        icon_color: green
      dining_room:
        name: Dining room
        icon_color: brown
      living_room:
        name: Reception room
        icon_color: green
      kitchen:
        name: Kitchen
        icon_color: red
      2nd_living_room:
        name: Breakfast Room
        icon_color: green
      front_house:
        name: Front house
        icon_color: brown
      garden:
        name: Garden
        icon_color: green
        extra_cards:
          - type: gauge
            name: Left side soil moisture
            unit: '%'
            min: 0
            max: 100
            needle: true
            entity: sensor.soild_sensor_left_side_soil_moisture
            severity:
              red: 0
              yellow: 30
              green: 70
            alignment: center
          - type: gauge
            name: Right bottom side soil moisture
            unit: '%'
            min: 0
            max: 100
            needle: true
            entity: sensor.soil_sensor_right_bottom_soil_moisture
            severity:
              red: 0
              yellow: 30
              green: 70
            alignment: center
          - type: gauge
            name: Right side soil moisture
            unit: '%'
            min: 0
            max: 100
            needle: true
            entity: sensor.soil_sensor_right_side_soil_moisture
            severity:
              red: 0
              yellow: 30
              green: 70
            alignment: center
      hallway_1st_floor:
        name: Hallway ground floor
      bathroom_kids:
        name: Bathroom kids
        icon_color: blue
      hallway_second_floor:
        name: Hallway first floor
      office:
        name: Iris Office
        icon_color: black
      bedroom:
        name: Romi room
        icon_color: pink
      master_bedroom:
        name: Master Bedroom
        icon_color: red
      bathroom_loft:
        name: Bathroom loft
    quick_access_cards:
      - type: vertical-stack
        cards:
          - type: weather-forecast
            entity: weather.pirateweather
            forecast_type: daily
            show_current: true
            show_forecast: true
          - type: custom:advanced-camera-card
            cameras:
              - camera_entity: camera.front_camera_clear
          - type: custom:advanced-camera-card
            cameras:
              - camera_entity: camera.camera1_clear
          - type: custom:advanced-camera-card
            cameras:
              - camera_entity: camera.front_door_doorbell_clear
      - type: vertical-stack
        cards:
          - type: custom:digital-clock
            dateFormat:
              weekday: long
              day: 2-digit
              month: short
            timeFormat:
              hour: 2-digit
              minute: 2-digit
          - type: custom:calendar-card-pro
            title: Events
            title_font_size: 40px
            week_number_font_size: 30px
            event_font_size: 25px
            time_font_size: 18px
            refresh_interval: 5
            refresh_on_navigate: true
            entities:
              - entity: calendar.family
                color: '#1e90ff'
            days_to_show: 5
            max_events_to_show: 12
            show_location: false
      - type: vertical-stack
        cards:
          - type: gauge
            name: Hot water
            unit: °
            min: 20
            max: 40
            needle: true
            entity: sensor.t_h_sensor_with_external_probe_probe_temperature
            severity:
              red: 0
              yellow: 28
              green: 32
          - type: todo-list
            entity: todo.todo_list
            title: Notes
            hide_completed: true
    extra_views:
      - theme: Backend-selected
        title: Batteries
        path: Batteries
        icon: mdi:battery-high
        cards:
          - type: custom:battery-state-card
      - theme: Backend-selected
        title: Water
        path: water
        icon: mdi:thermometer-water
        cards:
          - type: horizontal-stack
            cards:
              - type: vertical-stack
                style:
                  card:
                    width: 50%
                cards:
                  - type: gauge
                    name: Hot water
                    unit: °C
                    min: 20
                    max: 40
                    needle: true
                    entity: sensor.t_h_sensor_with_external_probe_probe_temperature
                    severity:
                      red: 0
                      yellow: 28
                      green: 32
                  - type: gauge
                    name: Hot water real
                    unit: °C
                    min: 20
                    max: 40
                    needle: true
                    entity: sensor.hot_water_device_temperature
                    severity:
                      red: 0
                      yellow: 27
                      green: 31
                  - type: entity-button
                    name: Hot water toggle
                    icon: mdi:water-boiler
                    entity: binary_sensor.hot_water_output
                    tap_action:
                      action: call-service
                      service: automation.trigger
                      target:
                        entity_id: automation.hot_water_toggle_automation
                  - type: history-graph
                    title: Hot Water temperatures (last 48 h)
                    hours_to_show: 48
                    entities:
                      - entity: >-
                          sensor.t_h_sensor_with_external_probe_probe_temperature
                        name: Hot water
                  - type: history-graph
                    title: Hot Water real temperatures (last 48 h)
                    hours_to_show: 48
                    entities:
                      - entity: sensor.hot_water_device_temperature
                        name: Hot water real
              - type: vertical-stack
                style:
                  card:
                    width: 50%
                cards:
                  - type: button
                    entity: switch.main_water
                  - type: button
                    entity: switch.garden_water
                  - type: custom:apexcharts-card
                    header:
                      show: true
                      title: Garden Water
                    graph_span: 7d
                    span:
                      end: day
                    series:
                      - entity: sensor.main_water
                      - entity: sensor.garden_irrigation_water
views: []
```
`

### Versions

- Mushroom Dashboard: v2.3.3 
- Lovelace Mushroom: 
- Home Assistant: 2025.5.3

### Environment

Web Browser (specify name and version)

### Expected Behavior

multiple columns in the UI 

### Actual Behavior

only one column 

### Error Logs (if applicable)

```plain text

```

### Guidelines

- [x] I have read and agree to the guidelines.
